version: '3.9'
services:
  database:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: 'admin-pg-user'
      POSTGRES_PASSWORD: '1234tttt'
      POSTGRES_DB: 'database'
      POSTGRES_MULTIPLE_DATABASES: 'database'
    networks:
      - backend
    ports:
      - "5431:5432"
    volumes:
      - database-pg:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
  
  api:
    build:
      context: ../Planning
      dockerfile: Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - database
    networks:
      - backend
    restart: always
    ports:
      - "8081:8080"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    depends_on:
      - database
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '82:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
      
      # Uncomment the next line if you uncomment anything in the section
      # environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

networks:
  backend:
    driver: bridge

volumes:
  database-pg: